LANGCHAIN_PROJECT="第３回金融庁データ利活用コンテスト"
WANDB_PROJECT="第３回金融庁データ利活用コンテスト"
pdf_file_path = "../documents"
CHUNK_SIZE=512
CHUNK_OVERLAP=50
OPENAI_EMBEDDING_MODEL="text-embedding-3-large"
OPENAI_MODEL = "gpt-4o-mini"
GEMINI_MODEL = "models/gemini-1.5-flash"
GEMINI_EMBEDDING_MODEL="models/embedding-001"
